#!/usr/bin/env bash

VERSION="2.0.1"
INPUT=
FINPUT=false
HEXFLAGS="-X"
PREFIX=
MODE=$(getconf LONG_BIT)
T_ASSEMBLER="fasm \\if \\of"
CONFIG=true


while getopts "a:cf:hp:x:" flag; do
        case $flag in
	a) 	T_ASSEMBLER="$OPTARG";;
	c)	CONFIG=false;;
        f)      if [[ $FINPUT = true ]]; then
                        echo "Error: Multiple file input."
                        exit 1
                fi
                INPUT="$OPTARG"
                FINPUT=true;;
        h)
                echo "Assemble $VERSION -- Lilly H. St Claire"
                echo "  A simple command line utility to quickly check"
                echo "  the assembled values of assembly expressions."
                echo "\n  Usage: assemble {OPTIONS}"
                echo "\nOptions:"
		echo "  -a <format text>"
		echo "    Replacing '\\if' with the input argument and '\\of' with the output"
		echo "    argument set the assembler."
		echo "  -c"
		echo "    Disables config loading."
                echo "  -f <file>"
                echo "    Reads input from file instead of user input."
                echo "  -p <prefix>"
                echo "    Prefix the output with the supplied prefix."
		echo "  -x <mode>"
		echo "    Sets mode."
		echo "\nConfig file:"
		echo "  The config file is to be stored at \$HOME/.assemble.config, and in the case"
		echo "  that it does, the following values may be set:"
		echo "    T_ASSEMBLER=x    Sets the value of -a."
		echo "    PREFIX=x         Sets the value of -p."
		echo "  Note that \$MODE may be used at any point in the config."
		;;
        p)      PREFIX="$OPTARG";;
	x)	MODE="$OPTARG";;
        esac
done

if [[ $CONFIG = true && -f "$HOME/.assemble.config" ]]; then
	. ~/.assemble.config
fi

rm -f /tmp/.assemble.input /tmp/.assemble.output
printf "$PREFIX" >> /tmp/.assemble.input
if [[ $FINPUT = false ]]; then
        echo "Enter assembly (CTR-D to conitnue):"
        cat >> /tmp/.assemble.input
else
	cat "$INPUT" >> /tmp/.assemble.input
fi

OIFS=$IFS
IFS=' '
ASSEMBLER=""
for readin in $T_ASSEMBLER
do
	if [[ "$readin" = "\\if" ]]; then
		ASSEMBLER="$ASSEMBLER /tmp/.assemble.input"
	elif [[ "$readin" = "\\of" ]]; then
		ASSEMBLER="$ASSEMBLER /tmp/.assemble.output"
	else
		ASSEMBLER="$ASSEMBLER $readin"
	fi
done
IFS=$OIFS

$ASSEMBLER

hexdump $HEXFLAGS /tmp/.assemble.output
rm -f /tmp/.assemble.input /tmp/.assemble.output
